---
title: "Movielens"
date: '`r Sys.time()`'
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)
library(ggplot2)

# set plot theme
theme_set(theme_bw())
```

# Load and preview data

Read data from the `ratings.csv` file
```{r load-data}
ratings <- read_csv('ratings.csv',
                    col_names = c('user_id','movie_id','rating','timestamp'))
```

Loaded `r format(object.size(ratings), units="Mb")` of ratings data, containing `r format(nrow(ratings), big.mark = ",")` ratings. Here's a preview:
```{r preview-data}
head(ratings) %>% kable()
```

# Summary statistics

```{r dist-ratings}
# plot the distribution of rating values https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=26
ratings |>
  select(rating) |>
  group_by(rating) |>
  summarize(num_rating = n()) |>
  ggplot(aes(x = rating, y = num_rating)) +
  geom_col() +
  scale_y_continuous(labels = comma)
```

## Per-movie stats

```{r aggregate-by-movie}
# aggregate ratings by movie, computing mean rating and number of ratings
# hint: use the n() function for easy counting within a group

ratings_agg_by_movie <- ratings |>
  group_by(movie_id) |>
  summarise(num_rating_per_movie = n(), mean_rating_per_movie=mean(rating))

ratings_agg_by_movie

  
# ratings_with_mean_rating <- ratings|> group_by(movie_id) |> summarise(mean_rating_per_movie=mean(rating))

# ratings_with_rating_per_rate_per_movie <- ratings|>
#   select(movie_id, rating) |>
#   group_by(movie_id, rating) |>
#   summarise(num_rating_per_rate_per_movie = n())

# ratings_for_mean <- left_join(ratings_with_rating_per_rate_per_movie, ratings_with_rating_per_movie)
# ratings_for_mean  

# ratings_agg_by_movie <- left_join(ratings_with_num_rating, ratings_with_mean_rating)

# ratings_agg_by_movie

```

```{r dist-movie-popularity}
# plot distribution of movie popularity (= number of ratings the movie received)
# hint: try scale_x_log10() for a logarithmic x axis

ratings_agg_by_movie |> 
  select(movie_id, num_rating_per_movie) |>
  rename(popularity = num_rating_per_movie) |>
  ggplot(aes(x = popularity)) +
  geom_histogram() +
  scale_x_log10()


```

```{r dist-mean-ratings-by-movie}
# plot distribution of mean ratings by movie https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=28
# hint: try geom_histogram and geom_density

ratings_agg_by_movie |>
  select(movie_id, mean_rating_per_movie) |>
  ggplot(aes(x = mean_rating_per_movie)) +
  geom_density(fill = "grey")

```

```{r cdf-movie-pop}
# rank movies by popularity (number of ratings) and compute the cdf, or fraction of all views covered by the top-k movies https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=30
# hint: use dplyr's rank and arrange functions, and the base R sum and cumsum functions
# store the result in a new data frame so you can use it in creating figure 2 from the paper below

ratings_agg_by_movie <- ratings_agg_by_movie |>
  rename(popularity = num_rating_per_movie)

ratings_cumulative_sum <- ratings_agg_by_movie |>
  select(movie_id, popularity) |>
  arrange(desc(popularity)) |>
  mutate(rank = row_number()) |>
  mutate(total_popularity = sum(popularity)) |>
  mutate(fraction_of_popularity = popularity / total_popularity) |>
  mutate(cumulative_population = cumsum(fraction_of_popularity)) |>
  mutate(cdf_population_percent = cumulative_population * 100)
ratings_cumulative_sum
 
# plot the CDF of movie popularity


ratings_cumulative_sum |>
  select(rank, cdf_population_percent) |>
  ggplot(aes(x = rank, y = cdf_population_percent)) +
  geom_line()


```


# Per-user stats

```{r aggregate-by-user}
# aggregate ratings by user, computing mean and number of ratings
ratings_agg_by_user <- ratings |>
  group_by(user_id) |>
  summarise(num_rating_per_user = n(), mean_rating_per_user = mean(rating))


```

```{r dist-user-activity}
# plot distribution of user activity (= number of ratings the user made)
# hint: try a log scale here
ratings_agg_by_user |>
  ggplot(aes(x = num_rating_per_user)) +
  geom_histogram() +
  scale_x_log10()
```

# Anatomy of the long tail

```{r long-tail}
# generate the equivalent of figure 2a of this paper:
# note: don't worry about the "null model" lines
# just do the solid lines and dotted line (optional)
# https://5harad.com/papers/long_tail.pdf

# Specifically, for the subset of users who rated at least 10 movies,
# produce a plot that shows the fraction of users satisfied (vertical
# axis) as a function of inventory size (horizontal axis). We will
# define "satisfied" as follows: an individual user is satisfied p% of
# the time at inventory of size k if at least p% of the movies they
# rated are contained in the top k most popular movies. As in the
# paper, produce one curve for the 100% user satisfaction level and
# another for 90%---do not, however, bother implementing the null
# model (shown in the dashed lines).

ratings_long_tail <- left_join(ratings, ratings_cumulative_sum)
ratings_long_tail

ratings_long_tail_1 <- ratings_long_tail |>
  group_by(user_id) |>
  summarise(rank_of_weirdest = max(rank)) |>
  arrange(rank_of_weirdest)

ratings_long_tail_1 <- ratings_long_tail_1 |> 
  group_by(rank_of_weirdest) |>
  summarize(num_per_rank_of_wiredest = n())

ratings_long_tail_1 <- ratings_long_tail_1 |>
  mutate(total_rank = sum(num_per_rank_of_wiredest)) |>
  mutate(percent_rank = (num_per_rank_of_wiredest / total_rank) *100) |>
  mutate(cdf_percent_rank = cumsum(percent_rank))
view(ratings_long_tail_1)


max_store_size <- max(ratings_long_tail$rank)
max_store_size

store_sizes <- data.frame(rank_of_weirdest = c(1:max_store_size))
head(store_sizes)

after_join_rank <-left_join(store_sizes, ratings_long_tail_1) |>
  fill(cdf_percent_rank)

view(after_join_rank)

after_join_rank |>
  ggplot(aes(x = rank_of_weirdest, y = cdf_percent_rank)) +
  geom_line()

```



```{r}
fig2 <-ratings_long_tail |>
  select(user_id, rank) |>
  arrange(user_id, rank)

# fig2 |> 
#   group_by(user_id) |>
#   mutate(num_per_user_id = n()) |>
#   mutate(ninety_percent = 0.9 * num_per_user_id)

fig2 <- fig2 |>
  group_by(user_id) |>
  slice_head(prop = 0.90)

fig2 <- fig2 |>
  group_by(user_id) |>
  summarise(rank_of_weirdest = max(rank)) |>
  arrange(rank_of_weirdest) |>
  group_by(rank_of_weirdest) |>
  summarize(num_per_rank_of_wiredest = n()) |>
  mutate(total_rank = sum(num_per_rank_of_wiredest)) |>
  mutate(percent_rank = (num_per_rank_of_wiredest / total_rank) *100) |>
  mutate(cdf_percent_rank = cumsum(percent_rank)) 


fig2_join_rank <-left_join(store_sizes, fig2) |>
  select(rank_of_weirdest, cdf_percent_rank) 

fig2_join_rank <- fig2_join_rank |>
  fill(cdf_percent_rank)

fig2 |>
  ggplot(aes(x = rank_of_weirdest, y = cdf_percent_rank)) +
  geom_line()



fig2_join_rank |>
  ggplot(aes(x = rank_of_weirdest, y = cdf_percent_rank)) +
  geom_line()

```



```{r}
ggplot() +
  geom_line(data = after_join_rank, aes(x = rank_of_weirdest, y = cdf_percent_rank, color= "100% Satisfaction")) +
  geom_line(data = fig2_join_rank, aes(x = rank_of_weirdest, y = cdf_percent_rank, color = "90% Satisfaction")) +
  scale_color_manual(values = c("100% Satisfaction" = "Blue", "90% Satisfaction" = " red"))
```





